### PR TITLE
Ssh agent forwarding Signed-off-by: Ioan Vranau ioan.vranau@hp.com

### PR DESCRIPTION
**Pull request by ioanvranau**

### CODE REVIEW

**Comment by meirwah** [comment]
Hi,
name of the branch is SSH  agent forwarding, 
but i see most of the commits are json related..

**Comment by meirwah** [comment]
adding @Bonczidai

**Comment by Bonczidai** [comment]
:+1:  tested agent forwarding
can you merge this PR?

**Comment by meirwah** [comment]
@ioanvranau are you still working on this PR? or is it ready?

**Comment by ioanvranau** [comment]
I was waiting for a code review. I will merge this soon

**Comment by ioanvranau** [comment]
The commits from json were somehow added from the other branch that was merged. So there is no connection between this two.

**Comment by ioanvranau** [comment]
Merged

**Pull request merged**
